"""Chinese backup copy for the English TUI text.

The active TUI is English-only for now. Keep these strings keyed by stable IDs
so a future localization pass can map prompts and descriptions without reading
git history.
"""

ZH_TEXT = {
    "app_title": "Newbie-image LoRA Modal 管理器",
    "main_menu": "你想做什么？",
    "main_run_training": "启动训练",
    "main_run_training_desc": "上传或复用输入内容，并启动一个 Modal 训练任务。",
    "main_download_output": "下载任务输出",
    "main_download_output_desc": "从 Modal Volume 下载已完成的 adapter 输出目录。",
    "main_load_model": "加载模型到 Volume",
    "main_load_model_desc": "将基础模型 snapshot 下载到 /workspace/Models。",
    "main_create_config": "创建配置",
    "main_create_config_desc": "为新任务生成 LoRA 或 LoKr TOML 配置。",
    "main_manage_volumes": "管理 Volume",
    "main_manage_volumes_desc": "列出、重命名、删除或打开 Modal Volume。",
    "main_quit": "退出",
    "main_quit_desc": "退出，不再执行其他操作。",
    "config_job_name": "配置/任务名称",
    "adapter_type": "Adapter 类型",
    "adapter_lokr_desc": "Newbie-image 训练质量优先的推荐默认选项。",
    "adapter_lora_desc": "更小的 adapter，适合更快、更省显存的实验。",
    "output_model_name": "输出模型名称",
    "training_resolution": "训练分辨率",
    "resolution_1024_desc": "平衡的默认选项。",
    "resolution_768_desc": "显存占用更低，迭代更快。",
    "resolution_1536_desc": "细节更高，但 GPU 成本更高。",
    "epochs": "训练轮数",
    "batch_size": "批大小",
    "learning_rate": "学习率",
    "training_config": "训练配置",
    "create_new_config": "创建新配置",
    "create_new_config_desc": "通过引导式问题创建一个新的 LoRA/LoKr 任务配置。",
    "modal_job_name": "Modal 任务名称",
    "first_upload_question": "这个数据集是第一次为此任务上传吗？",
    "first_upload_instruction": "只有当该任务的配置和数据集已经在 Modal Volume 中时才选择 No。",
    "dataset_directory": "本地训练集目录",
    "dataset_directory_instruction": "选择包含图片和 caption 的文件夹，并上传给这个任务。",
    "gpu": "GPU",
    "timeout_minutes": "超时时间（分钟）",
    "install_question": "训练前设置或更新 trainer 依赖吗？",
    "install_instruction": "首次运行或 trainer 更新后建议选择 Yes。只有远程环境已准备好时才选择 No。",
    "detach_question": "本地终端断开后是否继续训练？",
    "detach_instruction": "Detached 模式会提交任务并让 Modal 继续运行，本地会返回控制权。",
    "volume_management": "Volume 管理",
    "volume_list": "列出 Volume",
    "volume_list_desc": "显示当前账号可用的 Modal Volume。",
    "volume_delete": "删除 Volume",
    "volume_delete_desc": "永久删除一个 Volume 及其中全部数据。",
    "volume_rename": "重命名 Volume",
    "volume_rename_desc": "不下载内容，直接修改 Volume 名称。",
    "volume_dashboard": "打开 Dashboard",
    "volume_dashboard_desc": "在 Modal dashboard 中打开所选 Volume。",
    "back": "返回",
    "hf_repo": "Hugging Face 仓库或 URL",
    "revision": "Revision",
    "hf_secret": "包含 HF_TOKEN 的 Modal Secret 名称",
    "download_job_name": "训练时使用的 Modal 任务名称",
    "remote_output_override": "远程输出目录覆盖值",
    "local_destination": "本地保存目录",
}
